# Generated by Django 5.2.5 on 2025-08-16 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("message", models.TextField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("inquiry", "Inquiry"),
                            ("feedback", "Feedback"),
                            ("support", "Support"),
                            ("other", "Other"),
                            ("complaint", "Complaint"),
                            ("suggestion", "Suggestion"),
                            ("request", "Request"),
                            ("general", "General"),
                            ("urgent", "Urgent"),
                            ("follow-up", "Follow-up"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
    ]
