# Generated by Django 5.2.5 on 2025-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("inquiry", "Inquiry"),
                    ("register_course", "Register Course"),
                    ("other", "Other"),
                ],
                default="inquiry",
                max_length=100,
            ),
        ),
    ]
