# Generated by Django 5.2.5 on 2025-11-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_purpose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="updated_at",
        ),
    ]
