# Generated by Django 5.2.5 on 2025-11-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_contact_created_at_contact_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="is_deleted",
        ),
    ]
