# Generated by Django 5.2.5 on 2025-11-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_remove_contact_is_active_remove_contact_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="purpose",
            field=models.CharField(
                choices=[("inquiry", "Inquiry"), ("other", "Other")],
                default="inquiry",
                max_length=100,
            ),
        ),
    ]
