# Generated by Django 5.2.5 on 2025-11-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_pendinguser_is_active_pendinguser_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendinguser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="pendinguser",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="token",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="token",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
    ]
