# Generated by Django 5.2.5 on 2025-08-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_city_country_alter_dashboard_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default.png",
                null=True,
                upload_to="profile_pictures/%Y/%m/%d/",
            ),
        ),
    ]
