# Generated by Django 5.2.5 on 2025-08-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_dashboard_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/%Y/%m/%d/"
            ),
        ),
    ]
