# Generated by Django 5.2.5 on 2025-08-11 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_dashboard_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
