# Generated by Django 5.2.5 on 2025-08-14 16:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_dashboard_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="dashboard"
            ),
        ),
    ]
