# Generated by Django 5.2.5 on 2025-10-07 06:22

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_dashboard_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "about_image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="about"
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "About",
            },
        ),
    ]
