# Generated by Django 5.2.5 on 2025-08-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="post_images/%Y/%m/%d/"
            ),
        ),
    ]
