# Generated by Django 5.2.5 on 2025-10-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="views_count",
        ),
    ]
