# Generated by Django 5.2.5 on 2025-08-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_body_alter_post_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
